USE movies_db;
INSERT INTO movies (name, year, country) VALUES ('Властелин колец: Братство кольца', '2001', 'США');
INSERT INTO movies_genre (movie_id, genre_id) VALUES (1, 29);
INSERT INTO movies_genre (movie_id, genre_id) VALUES (1, 21);
INSERT INTO movies (name, year, country) VALUES ('Властелин колец: Две крепости', '2002', 'США');
INSERT INTO movies_genre (movie_id, genre_id) VALUES (2, 29);
INSERT INTO movies_genre (movie_id, genre_id) VALUES (2, 21);
INSERT INTO movies (name, year, country) VALUES ('Властелин колец: Возвращение короля', '2003', 'США');
INSERT INTO movies_genre (movie_id, genre_id) VALUES (3, 29);
INSERT INTO movies_genre (movie_id, genre_id) VALUES (3, 21);
INSERT INTO movies (name, year, country) VALUES ('Хоббит: Нежданное путешествие', '2012', 'США');
INSERT INTO movies_genre (movie_id, genre_id) VALUES (4, 29);
INSERT INTO movies_genre (movie_id, genre_id) VALUES (4, 21);
INSERT INTO movies (name, year, country) VALUES ('Хоббит: Пустошь Смауга', '2013', 'США');
INSERT INTO movies_genre (movie_id, genre_id) VALUES (5, 29);
INSERT INTO movies_genre (movie_id, genre_id) VALUES (5, 21);
INSERT INTO movies (name, year, country) VALUES ('Хоббит: Битва пяти воинств', '2014', 'США');
INSERT INTO movies_genre (movie_id, genre_id) VALUES (6, 29);
INSERT INTO movies_genre (movie_id, genre_id) VALUES (6, 21);
INSERT INTO movies (name, year, country) VALUES ('Пираты Карибского моря: Проклятие Черной жемчужины', '2003', 'США');
INSERT INTO movies_genre (movie_id, genre_id) VALUES (7, 21);
INSERT INTO movies_genre (movie_id, genre_id) VALUES (7, 29);
INSERT INTO movies (name, year, country) VALUES ('Пираты Карибского моря: Сундук мертвеца', '2006', 'США');
INSERT INTO movies_genre (movie_id, genre_id) VALUES (8, 21);
INSERT INTO movies_genre (movie_id, genre_id) VALUES (8, 29);
INSERT INTO movies (name, year, country) VALUES ('Пираты Карибского моря: На краю Света', '2007', 'США');
INSERT INTO movies_genre (movie_id, genre_id) VALUES (9, 21);
INSERT INTO movies_genre (movie_id, genre_id) VALUES (9, 29);
INSERT INTO movies (name, year, country) VALUES ('Пираты Карибского моря: На странных берегах', '2011', 'США');
INSERT INTO movies_genre (movie_id, genre_id) VALUES (10, 21);
INSERT INTO movies_genre (movie_id, genre_id) VALUES (10, 29);